"""add field page_number in scanned file

Revision ID: 5846ff81b551
Revises: c29a3dce60e6
Create Date: 2025-04-26 15:47:46.332421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5846ff81b551'
down_revision: Union[str, None] = 'c29a3dce60e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scannedfile', sa.Column('page_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scannedfile', 'page_number')
    # ### end Alembic commands ###
