"""Initial migration

Revision ID: b03cae1ed08f
Revises: 
Create Date: 2025-04-24 14:00:16.353246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03cae1ed08f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lima_number', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metatable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scannedfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabledata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('col_count', sa.Integer(), nullable=True),
    sa.Column('polygon', sa.JSON(), nullable=True),
    sa.Column('metatable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metatable_id'], ['metatable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('x_min', sa.Integer(), nullable=True),
    sa.Column('x_max', sa.Integer(), nullable=True),
    sa.Column('y_min', sa.Integer(), nullable=True),
    sa.Column('y_max', sa.Integer(), nullable=True),
    sa.Column('scanned_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scanned_file_id'], ['scannedfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablecell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('col_index', sa.Integer(), nullable=True),
    sa.Column('col_span', sa.Integer(), nullable=True),
    sa.Column('row_span', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('selectable', sa.Boolean(), nullable=True),
    sa.Column('tabledata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tabledata_id'], ['tabledata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tablecell')
    op.drop_table('file_region')
    op.drop_table('tabledata')
    op.drop_table('scannedfile')
    op.drop_table('metatable')
    op.drop_table('file')
    op.drop_table('project')
    # ### end Alembic commands ###
