"""add column files_to_scan

Revision ID: c29a3dce60e6
Revises: b03cae1ed08f
Create Date: 2025-04-26 15:18:31.011454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29a3dce60e6'
down_revision: Union[str, None] = 'b03cae1ed08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('files_to_scan', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'files_to_scan')
    # ### end Alembic commands ###
